apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: {{ .Values.namespace }}
data:
  config.json: |
{{ .Values.config | indent 4 }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: realm-export-config
  namespace: {{ .Values.namespace }}
data:
  realm-export-config.json: |
{{ .Values.realmexportconfig | indent 4 }}

